-- CreateTable
CREATE TABLE `USER` (
    `USER_CD_USER` VARCHAR(191) NOT NULL,
    `USER_TX_NAME` VARCHAR(191) NOT NULL,
    `USER_TX_EMAIL` VARCHAR(191) NOT NULL,
    `USER_TX_PASSWORD` VARCHAR(191) NOT NULL,
    `USER_DT_CREATED_AT` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `USER_DT_UPDATED_AT` DATETIME(3) NULL,

    UNIQUE INDEX `USER_USER_TX_EMAIL_key`(`USER_TX_EMAIL`),
    PRIMARY KEY (`USER_CD_USER`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `SESSION` (
    `SESS_CD_SESSION` VARCHAR(191) NOT NULL,
    `USER_CD_USER` VARCHAR(191) NOT NULL,
    `SESS_TX_TOKEN` VARCHAR(1600) NOT NULL,
    `SESS_TX_REFRESH` VARCHAR(1600) NOT NULL,
    `SESS_DT_CREATED_AT` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `SESS_DT_UPDATED_AT` DATETIME(3) NULL,

    UNIQUE INDEX `SESSION_USER_CD_USER_key`(`USER_CD_USER`),
    PRIMARY KEY (`SESS_CD_SESSION`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `USER_PASSWORD_RESET` (
    `USPR_CD_USER_PASSWORD_RESET` VARCHAR(191) NOT NULL,
    `USER_CD_USER` VARCHAR(191) NOT NULL,
    `USPR_TX_CODE` VARCHAR(500) NOT NULL,
    `USPR_DT_EXPIRES_AT` DATETIME(3) NOT NULL,
    `USPR_DT_CREATED_AT` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `USPR_DT_UPDATED_AT` DATETIME(3) NULL,

    UNIQUE INDEX `USER_PASSWORD_RESET_USPR_TX_CODE_key`(`USPR_TX_CODE`),
    PRIMARY KEY (`USPR_CD_USER_PASSWORD_RESET`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `NOTE` (
    `NOTE_CD_NOTE` VARCHAR(191) NOT NULL,
    `NOTE_TX_TITLE` VARCHAR(191) NOT NULL,
    `NOTE_TX_CONTENT` VARCHAR(191) NULL,
    `NOTE_DT_CREATED_AT` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `NOTE_DT_UPDATED_AT` DATETIME(3) NULL,
    `USER_CD_USER` VARCHAR(191) NOT NULL,
    `TOPI_CD_TOPIC` VARCHAR(191) NOT NULL,

    PRIMARY KEY (`NOTE_CD_NOTE`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `TOPIC` (
    `TOPI_CD_TOPIC` VARCHAR(191) NOT NULL,
    `TOPI_TX_NAME` VARCHAR(191) NOT NULL,
    `TOPI_DT_CREATED_AT` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `TOPI_DT_UPDATED_AT` DATETIME(3) NULL,
    `USER_CD_USER` VARCHAR(191) NOT NULL,

    PRIMARY KEY (`TOPI_CD_TOPIC`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `SESSION` ADD CONSTRAINT `SESSION_USER_CD_USER_fkey` FOREIGN KEY (`USER_CD_USER`) REFERENCES `USER`(`USER_CD_USER`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `USER_PASSWORD_RESET` ADD CONSTRAINT `USER_PASSWORD_RESET_USER_CD_USER_fkey` FOREIGN KEY (`USER_CD_USER`) REFERENCES `USER`(`USER_CD_USER`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `NOTE` ADD CONSTRAINT `NOTE_TOPI_CD_TOPIC_fkey` FOREIGN KEY (`TOPI_CD_TOPIC`) REFERENCES `TOPIC`(`TOPI_CD_TOPIC`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `NOTE` ADD CONSTRAINT `NOTE_USER_CD_USER_fkey` FOREIGN KEY (`USER_CD_USER`) REFERENCES `USER`(`USER_CD_USER`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `TOPIC` ADD CONSTRAINT `TOPIC_USER_CD_USER_fkey` FOREIGN KEY (`USER_CD_USER`) REFERENCES `USER`(`USER_CD_USER`) ON DELETE RESTRICT ON UPDATE CASCADE;
