#!/bin/sh

mysql -u root -p$MYSQL_ROOT_PASSWORD << EOF
CREATE DATABASE IF NOT EXISTS $MYSQL_DATABASE_SHADOW;
GRANT ALL PRIVILEGES ON $MYSQL_DATABASE_SHADOW.* TO '$MYSQL_USER'@'%';
FLUSH PRIVILEGES;
EOF
